set $bg_dim    #232a2e
set $bg0      #2d353b
set $bg1      #343f44
set $bg2      #3d484d
set $bg3      #475258
set $bg4      #4f585e
set $bg5      #56635f

set $bg_green      #425047

set $red      #e67e80
set $yellow    #dbbc7f
set $green    #a7c080
set $blue     #7fbbb3
set $purple   #d699b6
set $orange   #e69875
set $aqua   #83c092


set $grey0   #7a8478
set $grey1   #859289
set $grey1   #9da9a0
