#! /usr/bin/env bash

# Import the WAYLAND_DISPLAY env var from sway into the systemd user session.
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# Stop any servi that are running, so that they receive the new env var when they restart.
systemctl --user restart pipewire xdg-desktop-portal xdg-desktop-portal-wlr
